# NumPy

Numerical python, array işlemleri için özelleşmiş bir kütüphanedir. Bilimsel uygulamalar ve mühendislik için çok kullanışlıdır. ndarray olarak bilinen çok boyutlu matris yapısı ile ileri matematiksel işlemlere izin verir. Fourier transform ve linear cebir için özel fonksiyonları vardır. 

# List varken neden NumPy

NumPy bir python listesinden 50 kat daha hızlı işlenebilir. Numpy arrayleri hafızada sürekli bir alanda saklanır lokal referans olarak bilinen bu yapı süreci hızlandırır. NumPy cpu çalışması için optimizedir.

Bu iddiayı test edelim

In [15]:
import numpy as np
import time

# bir boyut seçelim
size = 100000000

# bu boyutta bir list ve numpy arrayı yaptık
list_data = list(range(size))
numpy_data = np.arange(size)

In [19]:
start = time.time()
newlist=[x * 2 for x in list_data]
end = time.time()
print(end - start)

14.210745096206665


In [18]:
start = time.time()
newnumpy=numpy_data * 2
end = time.time()
print(end - start)

0.20760798454284668


It is blazing fast, tıpkı tüm yeni js frameworkleri gibi :)

> NumPy objesi yaratmak

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [21]:
import numpy as np
#  Sıfır Boyutlu 
arr = np.array(42)

print(arr)

42


In [ ]:
import numpy as np
# bir boyut
arr = np.array([1, 2, 3, 4, 5])

print(arr)

In [ ]:
import numpy as np
# iki boyut
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

In [ ]:
import numpy as np
# 3 boyutlu
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

In [22]:
# boyut kontrol
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [23]:
import numpy as np
#beş boyutlu ma çoğu boş
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


> Değerlere Ulaşma  farkı

In [24]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
regularList=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

içi aynı olana bu iki yapıda 6 değerine ulaşmak için ne yapılır

In [26]:
print(regularList[0][1][2])


6


In [27]:
print(arr[0, 1, 2])


6


Normal sistemde sürekli işlere subscribe edilirken np arrayde bir adres susbscribe ediliyor.

> Dilimleme

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [29]:
newList = [1, 2, 3, 4, 5, 6, 7]
print(newList[1:5])



[2, 3, 4, 5]


slicingi yapması aynı tek boyutta ama çok boyutta işler değişir

In [31]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [32]:
newList=[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],
         [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
print(newList[1:3][ 1:4])

[[11, 12, 13, 14, 15]]


neden farklı sonuç verdi?  


np arrayda önce x ekseninde slice yapıldı ve iki adet array alındı sonrasında iki adet arrayda da slicing yapıldı.

In [33]:
print(newList[1:3])

[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


In [38]:
print(newList[1:3][0:1])

[[6, 7, 8, 9, 10]]


In [39]:
print(newList[1:3][0:2])

[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


ancak listede sising mantığı aynı eksende tekrar bir slicing yapıyor

Veri tipleri  

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )







In [40]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [41]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [44]:
import numpy as np
###a stringi integere dönüşemez hata alır
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [45]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


# Kopya Ve View