# NumPy

Numerical python, array işlemleri için özelleşmiş bir kütüphanedir. Bilimsel uygulamalar ve mühendislik için çok kullanışlıdır. ndarray olarak bilinen çok boyutlu matris yapısı ile ileri matematiksel işlemlere izin verir. Fourier transform ve linear cebir için özel fonksiyonları vardır. 

# List varken neden NumPy

NumPy bir python listesinden 50 kat daha hızlı işlenebilir. Numpy arrayleri hafızada sürekli bir alanda saklanır lokal referans olarak bilinen bu yapı süreci hızlandırır. NumPy cpu çalışması için optimizedir.

Bu iddiayı test edelim

In [ ]:
import numpy as np 
import time

# bir boyut seçelim
size = 100000000

# bu boyutta bir list ve numpy arrayı yaptık
list_data = list(range(size))
numpy_data = np.arange(size)

In [ ]:
start = time.time()
newlist=[x * 2 for x in list_data]
end = time.time()
print(end - start)

In [ ]:
start = time.time()
newnumpy=numpy_data * 2
end = time.time()
print(end - start)

It is blazing fast, tıpkı tüm yeni js frameworkleri gibi :)

# NumPy objesi yaratmak

In [ ]:
import numpy as np
oldList=[1, 2, 3, 4, 5]
arr = np.array(oldList)
print(oldList)
print(arr)

print(type(arr))

In [ ]:
import numpy as np
#  Sıfır Boyutlu 
arr = np.array(42)

print(arr)
print(type(arr))

In [ ]:
import numpy as np
# bir boyut
arr = np.array([1, 2, 3, 4, 5])

print(arr)

In [ ]:
import numpy as np
# iki boyut
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

In [ ]:
import numpy as np
# 3 boyutlu
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

In [ ]:
# boyut kontrol
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

In [ ]:
import numpy as np
#beş boyutlu ma çoğu boş
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

# Değerlere Ulaşma  farkı

In [20]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
regularList=[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [21]:
print(regularList[0])

[[1, 2, 3], [4, 5, 6]]


In [24]:
print(len(regularList))

2


In [22]:
print(regularList[0][1])

[4, 5, 6]


içi aynı olana bu iki yapıda 6 değerine ulaşmak için ne yapılır

In [23]:
print(regularList[0][1][2])


6


In [25]:
print(arr[0, 1, 2])


6


Normal sistemde sürekli işlere subscribe edilirken np arrayde bir adres susbscribe ediliyor.

# Dilimleme

In [31]:
import numpy as np

arr = np.array([0,1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[1 2 3 4]


In [32]:
newList = [0,1, 2, 3, 4, 5, 6, 7]
print(newList[1:5])



[1, 2, 3, 4]


slicingi yapması aynı tek boyutta ama çok boyutta işler değişir

In [33]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [34]:
newList=[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],
         [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
print(newList[1:3][ 1:4])

[[11, 12, 13, 14, 15]]


neden farklı sonuç verdi?  


np arrayda önce x ekseninde slice yapıldı ve iki adet array alındı sonrasında iki adet arrayda da slicing yapıldı.

In [35]:
print(newList[1:3])

[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


In [36]:
print(newList[1:3][0:1])

[[6, 7, 8, 9, 10]]


In [38]:
print(newList[1:3][0:2])

[[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


ancak listede slicing mantığı aynı eksende tekrar bir slicing yapıyor

 # Veri tipleri  

i - integer   
b - boolean   
u - unsigned integer  
f - float  
c - complex float  
m - timedelta  
M - datetime  
O - object  
S - string  
U - unicode string  
V - fixed chunk of memory for other type ( void )  







In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

<U11


In [48]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4] ,dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [60]:
import numpy as np
###a stringi integere dönüşemez hata alır
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [63]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1, 8.9])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3 8]
int32


# Kopya Ve View

In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [65]:
old_list = [1, 2, 3, 4, 5]
new_list = old_list.copy()
new_list[0] = 42
print(old_list)
print(new_list)

[1, 2, 3, 4, 5]
[42, 2, 3, 4, 5]


Listeden alıştığımız kopya mantığı numpyda aynen devam ediyor. Oluşan kopya farklı olduğu için kopya üzerindeki değişiklikler orijinali bozmaz.

In [66]:
old_list = [1, 2, 3, 4, 5]
new_list = old_list
new_list[0] = 42
print(old_list)
print(new_list)

[42, 2, 3, 4, 5]
[42, 2, 3, 4, 5]


In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Referans mantığı ise yine aynı şekilde çalışıyor. Burada yeni bir liste yerine referans verildiği için orijinal kaynak etkilenir. Çünkü ikinci "liste" aslında sadece birinciyi gösteren bir referans.

In [70]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Referans  (x = arr) aynı memory alanını gösteren iki ok oluşturur. View (x = arr.view()) ise aynı bilgilere sahip olan ve bir birine paralel kalan iki array oluşturur.

In [71]:
import numpy as np

# Create an original array
arr = np.array([1, 2, 3, 4, 5])

# Create a view
x = arr.view()

# Modify the view
x[0] = 99

print("\nOriginal array after modifying view:")
print("arr:", arr)  # Output: [99, 2, 3, 4, 5]
print("x:", x)      # Output: [99, 2, 3, 4, 5]

# Aynı obje mi 
print("\n arr ve x the aynı obje mi?")
print(arr is x)  # Output: False

print("x ve arr aynı içeriğe mi sahip?")
print(np.may_share_memory(arr, x))  # Output: True



Original array after modifying view:
arr: [99  2  3  4  5]
x: [99  2  3  4  5]

 arr ve x the aynı obje mi?
False
x ve arr aynı içeriğe mi sahip?
True


ancak view kullanmanın güzel yanı farklı sliceler oluşturabilmektir. Farklı metadataya ama aynı bilgiye sahip olan yeni x ndarrayı bize pencere sağlar.

In [73]:
import numpy as np

# Create an original array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a view by slicing
x = arr[:, 1:3]

print("\nOriginal array:")
print("arr:\n", arr)

print("\nView (sliced) array:")
print("x:\n", x)

# Modify the view
x[0, 0] = 99

print("\nOriginal array after modifying the view:")
print("arr:\n", arr)  # Note the change in arr
print("x:\n", x)      # Note the change in x
print(arr.shape)
print(x.shape)


Original array:
arr:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

View (sliced) array:
x:
 [[2 3]
 [5 6]
 [8 9]]

Original array after modifying the view:
arr:
 [[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]
x:
 [[99  3]
 [ 5  6]
 [ 8  9]]
(3, 3)
(3, 2)


# Boyut Işlemleri

boyut öğrenme

In [76]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [5, 6, 7, 8]])

print(arr.ndim)
print(arr.shape)

2
(3, 4)


bir boyuta zorlama

In [77]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


yeniden boyutlama

In [78]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [79]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


burada dikkat edilmesi gereken  içerik miktarıdır. shape(4.3) yaparken 4*3 = 12 element gerekir. shape (2 3 2 ) yaparken  2*3*2=12 element gerekir. Aşağıdaki örnekte shape(3 3) yapılacak. Yani 9 element gerekecek. Ancak biz 8 element vereceğiz.

In [80]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)
# NEDEN HATA VERDİ?
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

Peki reshape sonucu nedir? Reshape sonucu bir viewdir. Aynı datayı farklı metadata ile (slice shape) sunar.

In [81]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


Diyelim ki çok büyük sayıda elemanın var ve sen 2*2*x boyutunda bir array yapmak istiyorsun. X boyutu önemsiz ne kadar eleman varsa o kadar boyut alabilir. O zaman shape içinde x yerine -1 yaz. NumPy otomatik hesaplasın

In [82]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


aynı şekilde tek boyuta indirirken bu trick kullanılabilir.

In [83]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# For Döngüsü

In [84]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [85]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [86]:
arr = [[1, 2, 3], [4, 5, 6]]

for x in arr:
  print(x)

[1, 2, 3]
[4, 5, 6]


In [87]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [90]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [91]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


şimdi farklı bir şey deniyoruz. numpy itteratorü  

boyuta rağmen her tek elemana uğradı.

In [92]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [94]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [95]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Arrayları birleştirme

In [96]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)



[1 2 3 4 5 6]


In [97]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])


arr3 = np.concatenate((arr1, arr2), axis=0)
arr4 = np.concatenate((arr1, arr2), axis=1)
print(" Axis 0 için birleşme")
print(arr3)
print("Axis 1 için birleşme")
print(arr4)


 Axis 0 için birleşme
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Axis 1 için birleşme
[[1 2 5 6]
 [3 4 7 8]]


rowlarda işlem için

In [98]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


columnlarda işlem için

In [99]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


derinlikte işlem için

In [103]:
import numpy as np

arr1 = np.array([[1, 2, 3],[11, 12, 13]])

arr2 = np.array([[4, 5, 6],[21, 22, 23]])

arr = np.dstack((arr1, arr2))

print(arr)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[11 21]
  [12 22]
  [13 23]]]


# Arrayları Ayırtma

In [104]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

#3 parçaya ayır
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [105]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [108]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)
print("####")
print(newarr[0])
print("####")
print(newarr[1])
print("####")
print(newarr[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
####
[[1 2]
 [3 4]]
####
[[5 6]
 [7 8]]
####
[[ 9 10]
 [11 12]]


In [109]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


şuana kadar bi axis kontrolümüz olmadan böldük

şimdi rowlardan bölcez. Her rowdan parça alarak 

In [115]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)



print("####")
print(newarr[0])
print("####")
print(newarr[1])
print("####")
print(newarr[2])

####
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
####
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
####
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [117]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)



print(newarr[0])
print("####")
print(newarr[1])
print("####")
print(newarr[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
####
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
####
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [118]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr[0])
print("####")
print(newarr[1])
print("####")
print(newarr[2])


[[1 2 3]
 [4 5 6]]
####
[[ 7  8  9]
 [10 11 12]]
####
[[13 14 15]
 [16 17 18]]


In [121]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])

newarr = np.dsplit(arr, 3)

print(arr)
print("####")
print(newarr[0])
print("####")
print(newarr[2])




[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
####
[[[ 1]
  [ 4]]

 [[ 7]
  [10]]

 [[13]
  [16]]]
####
[[[ 3]
  [ 6]]

 [[ 9]
  [12]]

 [[15]
  [18]]]


dsplitte 3 boyutlu arrayda çalışır

# Arrayda Arama Yapmak

In [122]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [130]:
arr = np.array([41, 42, 43, 44])
x = np.where(arr > 42)
print(x)

(array([2, 3], dtype=int64),)


In [123]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


where içini true yapan koşullar bulunur ve adressleri yazılır

eğer sıralı bir listen varsa binary her şeyi hızlandırır.  
searchsorted ile sıralı listede binary search yapabilirsin

In [ ]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

# Sıralama 

In [124]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [125]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filtreleme

In [126]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)


[41 43]


In [129]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42


# bu işlemin çok benzeri pandas ile de yapılıyor
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
